---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - db.weaviate.io
  resources:
  - weaviates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.weaviate.io
  resources:
  - weaviates/finalizers
  verbs:
  - update
- apiGroups:
  - db.weaviate.io
  resources:
  - weaviates/status
  verbs:
  - get
  - patch
  - update
