# permissions for end users to view weavites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: weavite-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: weaviate-operator
    app.kubernetes.io/part-of: weaviate-operator
    app.kubernetes.io/managed-by: kustomize
  name: weavite-viewer-role
rules:
- apiGroups:
  - db.weaviate.io
  resources:
  - weavites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.weaviate.io
  resources:
  - weavites/status
  verbs:
  - get
