apiVersion: db.weaviate.io/v1alpha1
kind: Weavite
metadata:
  labels:
    app.kubernetes.io/name: weavite
    app.kubernetes.io/instance: weavite-sample
    app.kubernetes.io/part-of: weaviate-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: weaviate-operator
  name: weaviate-test
  namespace: default
spec:
  replicas: 1
  # TODO(user): Add fields here
